import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { AppProviders } from '@/components/AppProviders'
import { SidebarProvider } from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/app-sidebar'
import { Breadcrumb } from '@/components/ui/breadcrumb'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PrivateLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppProviders>
          <SidebarProvider>
            <div className="flex min-h-screen flex-col">
              <div className="bg-white w-full" />
              <div className="flex flex-1">
                <AppSidebar />
                <main className="flex-1 min-w-0 flex flex-col">
                  <div className="px-6 pt-6">
                    <Breadcrumb />
                  </div>
                  <div className="border-b border-gray-300 w-full" />
                  {children}
                </main>
              </div>
            </div>
          </SidebarProvider>
        </AppProviders>
      </body>
    </html>
  )
} 