describe('Accès à la page admin selon le rôle', () => {
  it('refuse l\'accès à /admin pour un utilisateur non admin', () => {
    cy.visit('/login')
    cy.get('input[name="email"]').type('user@demo.com')
    cy.get('input[name="password"]').type('user1234')
    cy.get('button[type="submit"]').click()
    cy.wait(1000)
    cy.reload()
    cy.wait(1000)
    cy.url().should('satisfy', (url) => url.includes('/login') || url.includes('/dashboard'))
    cy.visit('/admin', { failOnStatusCode: false })
    cy.url().should('not.include', '/admin')
    cy.url().should('include', '/dashboard')
    cy.get('[data-cy="main-nav"] [data-cy="nav-admin"]').should('not.exist')
  })

  it('autorise l\'accès à /admin pour un admin', () => {
    cy.visit('/login')
    cy.get('input[name="email"]').type('angelo.geraci@soprism.com')
    cy.get('input[name="password"]').type('admin1234')
    cy.get('button[type="submit"]').click()
    cy.url().should('not.include', '/login')
    cy.reload()
    cy.get('[data-cy="main-nav"] [data-cy="nav-admin"]', { timeout: 20000 }).should('exist')
  })
}) 